### PR TITLE
Fan control works!

### PR DESCRIPTION
**Pull request by TheBum**
Fan control settings can be changed by PUTing a JSON blob to Pi3:5000/casefan.
The blob can be partial or full and has the following fields defined:

"control": "on" (fan control enabled) or "off" (default: "off").
"threshold": fan start temperature in ºC (default: 37).
"hysteresis": fan stop temperature delta from the threshold temp (default: 3).
"gpio": the GPIO output number to use (NOT the header pin number) (default: 23 = header pin 16).

Fan control settings can be queried using GET Pi3:5000/casefan.
All settings are returned in a JSON blob plus the current running state of the fan ("running": true or false).

I have added a PNG of the circuit schematic to docs/images.

### CODE REVIEW

**Comment by TheBum** [comment]
I have also worked up a wiring diagram using a prototyping circuit board that I could add to the docs images. In fact, I used it to wire up a second header socket with the circuit board extending toward the interior of the Pi 3 instead of hanging off the outside (the first attempt was done "on the fly" and I failed to account for flipping over the header socket). I will often get prototyping boards with pre-etched traces and cut them up as needed for small circuits because they mostly eliminate the need to run wires, thereby adding an element of neatness.

**Comment by TheBum** [comment]
There's a slight conflict between my prototype board wiring diagram and the potential iBump controller that I'll have to work out before I commit it.

**Comment by scornflake** [comment]
Hey Alan, I've committed a bunch of stuff to this branch. Added in a typed 'CaseFan' model object, which is then used in the REST interface. It provides some type and value safety.  Small refactorings otherwise. I'll merge to master!

**Comment by TheBum** [comment]
I’m confused. I don’t see any new commits to my fork when I look at it on GitHub.

Alan

**Comment by scornflake** [comment]
Do they appear on your fork directly? Perhaps they are not included in this particular pull request. Perhaps we have to create another pull request to have them "seen" by github?

**Comment by scornflake** [comment]
btw: one breaking change will be "control" is now a boolean in the JSON. Don't use 'on' / 'off', use true and false instead.

**Pull request merged**
